### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by asabil** [Igalia/cog#87] opened 2019-04-10 21:35 UTC
We are experimenting with using cog using the wpe-fdo backend, and we are experiencing a file descriptor leak:

listing the file descriptors at about 1 / second
```
# ls -l /proc/709/fd | wc -l
625
# ls -l /proc/709/fd | wc -l
627
# ls -l /proc/709/fd | wc -l
631
# ls -l /proc/709/fd | wc -l
631
# ls -l /proc/709/fd | wc -l
635
# ls -l /proc/709/fd | wc -l
635
# ls -l /proc/709/fd | wc -l
639
```

listing of the file descriptors:
```
lrwx------    1 root     root            64 Apr 10 21:30 81 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 810 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 811 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 812 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 813 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 814 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 815 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 816 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 817 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 818 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 819 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 82 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 820 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 821 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 822 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 823 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 824 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 825 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 826 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 827 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 828 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 829 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 83 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 830 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 831 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 832 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 833 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 834 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 835 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 836 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 837 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:33 838 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 84 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 85 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 86 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 87 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 88 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 89 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:29 9 -> anon_inode:[eventfd]
lrwx------    1 root     root            64 Apr 10 21:30 90 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 91 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 92 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 93 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 94 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 95 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 96 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 97 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 98 -> anon_inode:dmabuf
lrwx------    1 root     root            64 Apr 10 21:30 99 -> anon_inode:dmabuf
```

Is there anything we might be doing wrong? Maybe an incorrect configuration?

**Comment by zdobersek** [comment] 2019-04-15 06:52
Are you running this on an iMX platform, with the imx-gpu-viv drivers?

**Comment by RajeshBhandari** [comment] 2019-04-15 07:00
yes , its on imx8m with imx-gpu-viv drivers

**Comment by RajeshBhandari** [comment] 2019-04-15 07:02
FYI :
Same issue was posted by somebody on wayland [https://bugs.freedesktop.org/show_bug.cgi?id=100298](https://bugs.freedesktop.org/show_bug.cgi?id=100298)
They marked it as "RESOLVED NOTOURBUG"

**Comment by philn** [comment] 2019-04-15 08:20
I can't reproduce this issue here on i.MX6 with etnaviv.

**Comment by philn** [comment] 2019-04-15 08:25
it's not our bug either, please refer to the imx-gpu-viv driver maintainers :)

**Closed** 2019-04-15 19:15 UTC

**Comment by zdobersek** [comment] 2019-04-15 20:17
To provide more insight, the issue is with the imx-gpu-viv drivers -- if I recall correctly, the issue occurs in the eglCreateWaylandBufferFromImageWL implementation. This function normally duplicates the file descriptor that's associated with the buffer resource, but the original file descriptor is not closed here, causing the leak to occur.

This is handled as expected in the Mesa implementation, where create_wl_buffer (called from dri2_wl_create_wayland_buffer_from_image) properly cleans up file descriptors:
https://gitlab.freedesktop.org/mesa/mesa/blob/master/src/egl/drivers/dri2/platform_wayland.c#L1095
https://gitlab.freedesktop.org/mesa/mesa/blob/master/src/egl/drivers/dri2/platform_wayland.c#L838

The frequency of leaks should correspond to screen updates done by the Web content -- if running some very active content at 60FPS, you'll need about 18 seconds to hit the 1024 fd limit. Increasing that limit is not really helpful here since every resource still stays alive, clogging up memory.

If your content is size-persistent, meaning the WPE view is not being resized frequently (i.e. cog stays the same size), then one possible workaround is to cache the buffers as they are imported. The EGL implementations normally create a small pool of buffers and then render interchangeably into buffers from that pool. This means that cog ends up working with the same small set of buffer resources for which we can execute the necessary transformation operations and cache those results.

This way we limit somewhat the amount of leaked file descriptors. Frequent resizing would likely break that since usually buffers are destroyed and recreated to address the new size of the rendering window (I think that's at least how Mesa does it, not sure about imx-gpu-iv).

This caching approach is implemented in the buffer-caching branch:
https://github.com/Igalia/cog/tree/zdobersek/buffer-caching
Feel free to try it out and see if the buffer leak is minimized to the point of usability.

I'm unsure this specific variant of caching implementation makes sense for Cog right now. The current plan is to move it over to the WPEBackend-fdo library and implement it behind a new, simpler EGLImage exporting API.

And obviously, the main issue should be reported upstream, but I first have to locate the appropriate bug tracker. FWIW the issue started appearing with the version of the drivers that was included in `sumo` releases.

**Comment by asabil** [comment] 2019-04-16 18:57
Thank you very much for looking into this. We will try the suggested branch, and potentially switch to etnaviv.

**Comment by RajeshBhandari** [comment] 2019-04-17 10:27
Thanks @zdobersek 
I have not checked the etnaviv drivers, but your branch "buffer-caching" solves the problem for us as we do not have any resizing scenarios.
