### ISSUE TITLE
Out of memory on wayland platform

### ISSUE THREAD

**Issue by tonyakiki** [Igalia/cog#538] opened 2023-02-17 09:28 UTC
We have noticed a memory leak when running cog with WL platform. It is a Yocto Linux with wayland/weston and Cog/wpewebkit showing a full screen website with some video playing together with some other graphics and the HW is an intel based platform.

We can see with /proc/meminfo that the memory is listed as “Cached” and “Unevictable”. With /sys/kernel/debug/dri/0/i915_gem_objects we can see that shrinkable objects and size goes slowly up and closely match the values in meminfo. It constantly goes up and down a bit but over time it goes up with 1-2 objects every 10 sec or so. The machine with 4GB reaches OOM after 1-2h.

Running versions:
- cog 0.16.1 (WPE WebKit 2.38.3)
- vainfo: VA-API version: 1.14 (libva 2.14.0)
- vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.3.1 (6547f4658)

Some observations we have seen so far.
- We don’t see the problem on all Intel platforms for instance it works on Intel Broxton (Gen9) but we do have problem on 
    - Intel Geminilake (Gen9)
    - Intel Elkhartlake (Gen11)
    - Intel Jasperlake (Gen11)
- We see the problem on some web sites but other not, but they can look very similar with video etc.
- We don’t see the problem if we turn off Weston and running Cog/webkit with drm platform.
- The memory/gem objects are released if Cog is closed.

Typically a while before the OOM notice the high buff/cache
![image](https://user-images.githubusercontent.com/47389714/219692150-98847864-b80b-4519-a09e-1dbea3c3bfad.png)

**Comment by philn** [comment] 2023-02-17 18:19
The fact that the leak happens on some platforms but not all you tested might indicate a driver issue. Needs further investigation...

**Comment by tonyakiki** [comment] 2023-02-22 09:21
As I mentioned previously the memory leak does not exist on DRM platform. How can we investigate further if this is a driver issue or cog / webkit issue? 
I run cog with WEBKIT_SAMPLE_MEMORY=1 and i could confirm the leak

**Comment by aperezdc** [comment] 2023-02-28 13:34
@tonyakiki Which versions/commits of WPEBackend-fdo and Cog were you using when the leak was observed? We have recently landed https://github.com/Igalia/WPEBackend-fdo/pull/178 and https://github.com/Igalia/WPEBackend-fdo/pull/181 around the timeof your original report&mdash;I wonder if you have found a regression, or if you are using a packaged release maybe the first of these PRs solves the issue.

**Comment by tonyakiki** [comment] 2023-03-01 08:15
I am using:
cog 0.16.1 (d2f817c)
wpebackend-fdo 1.14.0 (966b37d)
I'll try these patches and get back with a report. Thanks for your advice!

**Comment by aperezdc** [comment] 2023-03-01 09:46
> I am using:
> cog 0.16.1 ([d2f817c](https://github.com/Igalia/cog/commit/d2f817c7a51a7e72dd90c3c0137f5ef135974ea7))
> wpebackend-fdo 1.14.0 ([966b37d](https://github.com/Igalia/WPEBackend-fdo/commit/966b37dc908df07fc7c6a49ccd103edaa6c17dab))

These are indeed from before the fixes.

> I'll try these patches and get back with a report. Thanks for your advice!

Excellent, thanks! Looking forward to your results, and hoping that the issue is gone 👍🏼

**Comment by tonyakiki** [comment] 2023-03-03 07:20
I confirm that https://github.com/Igalia/WPEBackend-fdo/pull/178 and https://github.com/Igalia/WPEBackend-fdo/pull/181 fix the memory leak problem. 
@aperezdc when can we expect a release of these fixes?

**Comment by aperezdc** [comment] 2023-03-04 22:05
> I confirm that [Igalia/WPEBackend-fdo#178](https://github.com/Igalia/WPEBackend-fdo/pull/178) and [Igalia/WPEBackend-fdo#181](https://github.com/Igalia/WPEBackend-fdo/pull/181) fix the memory leak problem.
> @aperezdc when can we expect a release of these fixes?

Thanks a lot for confirming that these patches fixed the issue! I have just tagged and uploaded [WPEBackend-fdo 1.14.1](https://wpewebkit.org/release/wpebackend-fdo-1.14.1.html), which includes them.

**Closed by aperezdc** 2023-03-04 22:05 UTC
Labels: bug, upstream

**Comment by tonyakiki** [comment] 2023-03-07 09:01
Hello again @aperezdc ! I am using [meta-webkit](https://github.com/Igalia/meta-webkit) and I see that /recipes-browser/wpebackend-fdo still missing the last release 1.14.1. Can you confirm that? and when will it be released there?

**Comment by aperezdc** [comment] 2023-03-07 09:30
> Hello again @aperezdc ! I am using [meta-webkit](https://github.com/Igalia/meta-webkit) and I see that /recipes-browser/wpebackend-fdo still missing the last release 1.14.1. Can you confirm that? and when will it be released there?

I have just submitted a PR to get the update into `meta-webkit`: https://github.com/Igalia/meta-webkit/pull/455 &mdash; it should be quick to have it reviewed and merged, hopefully.
