### ISSUE TITLE
Cog fails to render local html file.

### ISSUE THREAD

**Issue by jameshilliard** [Igalia/cog#73] opened 2019-01-03 02:12 UTC
When I start cog with a local file as the url I get the raw html text instead of the rendered html.

This is how I'm launching cog:
```
/bin/cog --platform=fdo file:///var/www/frontend/index.html
```
Is this a bug or am I launching cog with the wrong options?

**Comment by aperezdc** [comment] 2019-01-07 21:21
@jameshilliard I think you might be missing the `shared-mime-info` package, which is used by WebKit in a few places for detecting MIME types. When content is loaded over HTTP(S), the `Content-Type` headers returned by the server are used, but that is not available when loading local files. Could you make sure that the package is installed and try again? Thanks!

**Comment by jameshilliard** [comment] 2019-01-07 21:49
Yep, installing that fixed it, might make sense to have cog log a warning if `shared-mime-info` isn't installed when trying to load from the filesystem if that's not too difficult.

**Comment by jameshilliard** [comment] 2019-01-07 22:06
So another weird issue has appeared, it seems that sometimes I get a blank white screen and it either doesn't load or takes a very long time to load. Any idea what might be causing that?

**Comment by jameshilliard** [comment] 2019-01-07 22:36
> Which distro are you using, by the way?

Buildroot with my `BR2_EXTERNAL` package configs based on [this](https://github.com/Igalia/buildroot-wpe). I did bump some package versions and am using 1.1.0 for `WPEBackend-fdo`.

> Maybe we can escalate a bug to make sure package dependencies are correct.

So `select BR2_PACKAGE_SHARED_MIME_INFO` should probably be added to that repo, although I'm not exactly sure which specific package it should be added to. Maybe [this](https://github.com/Igalia/buildroot-wpe/blob/master/package/wpewebkit/Config.in) one?

> The issue I found was an error on my side, not a WPEBackend-fdo regression :)

Can you give me details on what the error was?

> The error from xkbcommon is unrelated to the blank window/screen and is practically harmless.

Yeah, I suspected that was likely unrelated, it was just the only warning I was seeing in my logs.

**Comment by philn** [comment] 2019-01-07 22:38
I was setting the webview settings property wrongly.

**Comment by jameshilliard** [comment] 2019-01-07 22:46
Hmm, so it seems the slow loading generally seems to only happen once, then every time I restart cog after that it's fast, is there some sort of cache being built? The update framework I use works by replacing the full root filesystem for every update which causes the problem to return on each update.

**Comment by jameshilliard** [comment] 2019-01-07 23:02
I found out why it was taking so long to load...apparently for some reason the page won't render until the random number generator finishes initializing(which for some reason takes over 10 minutes on my system). The page immediately loads after I see `kernel: random: crng init done` in the kernel logs. I have [systemd-random-seed](https://www.freedesktop.org/software/systemd/man/systemd-random-seed.service.html) enabled which was causing the problem to not appear for normal reboots and only when I flashed an update which would wipe out the rootfs and saved seed.

**Comment by aperezdc** [comment] 2019-01-07 23:23
@jameshilliard A few notes:

- In the Buildroot overlay the `shared-mime-info` package is *not* selected automatically because it takes space on the generated images and it's not always needed (for example if always loading resources from the network) — in general we try to allow trimming down images generated with Buildroot as much as possible. I guess we could at least add a comment in the configuration menus with a tip about the package being optional when it's not selected by the user.

- Cog places the on-disk page cache under `$XDG_CACHE_HOME/cog/WebKitCache`.

I understand that now that you found out about the initialization of the random number generator all is working normally for you. Right?

**Comment by aperezdc** [comment] 2019-01-07 23:35
@jameshilliard Thanks for the confirmation, I suppose then we can close this issue. Please feel free to reopen it if needed.

**Closed** 2019-01-07 23:35 UTC
Labels: needs investigation, question

**Comment by austinchenji** [comment] 2022-02-24 05:48
> /bin/cog --platform=fdo --enable-write-console-messages-to-stdout=true --allow-file-access-from-file-urls=true --allow-universal-access-from-file-urls=true --dir-handler=file:///var/www/frontend /

@jameshilliard and @aperezdc, is this command line still valid for cog 0.12.0?
I got this warning below:

_Registering special URI scheme file is no longer allowed_

So I guess the command line has been changed. So what is it like if I want to load a local html file?

**Comment by jameshilliard** [comment] 2022-02-24 07:10
Try this:
```/bin/cog --platform=wl --enable-write-console-messages-to-stdout=true --allow-file-access-from-file-urls=true --allow-universal-access-from-file-urls=true --dir-handler=app:/var/www/frontend app://```

**Comment by austinchenji** [comment] 2022-02-24 08:29
> Try this: `/bin/cog --platform=wl --enable-write-console-messages-to-stdout=true --allow-file-access-from-file-urls=true --allow-universal-access-from-file-urls=true --dir-handler=app:/var/www/frontend app://`

@jameshilliard, thanks. In this case, the warning dispeared. But it looks like the directory is not correct. I used the command below:
```
bin/cog --platform=wl --enable-write-console-messages-to-stdout=true --allow-file-access-from-file-urls=true --allow-universal-access-from-file-urls=true --dir-handler=app:/ app://var/www/frontend/index.html
```
But still the page cannot be loaded successfully.
The error is like that:
"Page load error"
"Frame load interrupted"
Any ideas?

Another question is that for now `shared-mime-info` is a must or not to load local file? Since I load `cog` in an embeded device, it needs time to porting `shared-mime-info` to the device. So maybe there is some straightforward way to go?

**Comment by jameshilliard** [comment] 2022-02-24 10:25
> Another question is that for now `shared-mime-info` is a must or not to load local file?

It's required AFAIU.

**Comment by austinchenji** [comment] 2022-02-25 01:03
> Try this: `/bin/cog --platform=wl --enable-write-console-messages-to-stdout=true --allow-file-access-from-file-urls=true --allow-universal-access-from-file-urls=true --dir-handler=app:/var/www/frontend app://`

By this command, it cause error like below:
```
(cog:1): Cog-Core-WARNING **: 01:00:08.019: <app:///> Page load error: Frame load interrupted
```
It looks like wpe does not find the correct file /var/www/frontend/index.html. Any ideas?

**Comment by jameshilliard** [comment] 2022-02-25 01:12
> By this command, it cause error like below:

Is `shared-mime-info` installed when you get that error?

**Comment by austinchenji** [comment] 2022-02-25 06:28
> Is `shared-mime-info` installed when you get that error?

After installed `shared-mime-info`, the local file can be loaded now. Thanks, @jameshilliard.

Still I have a question, why does cog or wpewebkit forbidden to setup the scheme `file:///`? 
So for any local file loading, the scheme has to be changed to "app", right?

**Comment by jameshilliard** [comment] 2022-02-25 06:49
> Still I have a question, why does cog or wpewebkit forbidden to setup the scheme `file:///`?
> So for any local file loading, the scheme has to be changed to "app", right?

See #195 for details.

**Comment by austinchenji** [comment] 2022-02-25 08:10
> See #195 for details.

Thanks. I found a comment in #195 :
> Alternatively, if you want to load content using `file://` URIs, you can just remove `--dir-handler=` from the command line. This should work as well:
> 
> ```shell
> cog ... file:///var/www/frontend/index.html
> ```
Is it still valid? In my testing, it does not work since the scheme handler cannot be setup.

**Comment by aperezdc** [comment] 2022-02-25 08:39
> > See #195 for details.
> 
> Thanks. I found a comment in #195 :
> 
> > Alternatively, if you want to load content using `file://` URIs, you can just remove `--dir-handler=` from the command line. This should work as well:
> > ```shell
> > cog ... file:///var/www/frontend/index.html
> > ```
> 
> Is it still valid? In my testing, it does not work since the scheme handler cannot be setup.

Usage of `file://` URIs is always enabled, you don't need to pass a `--dir-handler=file:...` flag for it. Meaning, don't do this:

```sh
cog --platform=wl --dir-handler=file:/opt/webapp file:///opt/webapp/index.html
```

Instead, just do:

```sh
cog --platform=wl file:///opt/webapp/index.html
```

**Comment by austinchenji** [comment] 2022-02-28 08:45
> Instead, just do:
> 
> ```shell
> cog --platform=wl file:///opt/webapp/index.html
> ```

Thanks, @aperezdc. But by this way, the local file cannot be loaded successfully. The error is:
```
Frame load interrupted
```
I do not know why. Just see something like below:
```
1475 16:34:02.160 wpe(416) None: WPEWebKit::Network Debug: 0x68b398 - [resourceLoader=0x7fbc58, frameLoader=0x711cc0, frame=0x6d6ac8, webPageID=8, frameID=3, resourceID=1] WebLoaderStrategy::scheduleLoad: URL will be scheduled with the NetworkProcess
1476 16:34:02.160 wpe(416) None: WPEWebKit::Network Debug: 0x68b398 - [resourceLoader=0x7fbc58, frameLoader=0x711cc0, frame=0x6d6ac8, webPageID=8, frameID=3, resourceID=1] WebLoaderStrategy::scheduleLoad: Resource is being scheduled with the NetworkProcess (priority=4, existingNetworkResourceLoadIdentifierToResume=0)
1477 16:34:02.163 wpe(416) None: WPEWebKit::Network Debug: 0x76b5c0 - [webPageID=8, frameID=3, resourceID=1] WebResourceLoader::didReceiveResponse: (httpStatusCode=0)
1478 16:34:02.164 wpe(416) None: WPEWebKit::Loading Debug: 0x7105d0 - [webPageID=8] WebPage::didReceivePolicyDecision: policyAction=2 - frameID=3 - webFrame=0xb1004170 - mainFrame=1
1479 16:34:02.165 wpe(416) None: WPEWebKit::Network Debug: 0x7aa4e8 - [pageID=8, frameID=3, main=1] DocumentLoader::cancelMainResourceLoad: (type=3, code=102)
```
But with the way @jameshilliard given, the local file can be loaded successfully.
Maybe a regression in somewhere?
