### ISSUE TITLE
Is the defalut user agent string correct?

### ISSUE THREAD

**Issue by austinchenji** [Igalia/cog#496] opened 2022-09-22 06:15 UTC
I am working on wpewebkit 2.34.1.
I got the default user agent string like that "Mozilla/5.0 (Linux armv71 AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0  Safari/605.1.15)" on it. But when I checked the code base of [webkit ](https://trac.webkit.org/browser#webkit/tags), [Safari-605.1.15](https://trac.webkit.org/browser/webkit/tags/Safari-605.1.15) is five years ago. So is the default UA string accurate?
The file UserAgentGlib.cpp hardcode the string with 605.1.15 for a long term without any change.
` uaString.append(") AppleWebKit/605.1.15 (KHTML, like Gecko) ");`

The second qustion is how to know the mapping between wpewebkit/webkitGTK and webkit trunk or tags? I cannot find any webkit version information in wpewebkit release. Thanks in advance.

**Comment by philn** [comment] 2022-09-22 18:25
I think the UA was partly frozen several years ago indeed, and it was intended. You shouldn't do UA sniffing. You can override the UA if needed, using the corresponding web-setting.

wpe/gtk stable branches AFAIK don't map with Safari branches. Current stable branch is https://github.com/WebKit/WebKit/wiki/GLib-Stable-Branches and older ones can be found in Trac/Wiki/SVN.

**Comment by austinchenji** [comment] 2022-09-23 02:24
Thanks, @philn.

wpe/gtk may not map to any Safari branch, as you said. But it should be from a commit from webkit main branch. Then how can I find the relationship between the wpe release, such as 2.34.1 and webkit main branch? I want to know this because it may indicate how new the webkit core in wpe release is.

**Comment by philn** [comment] 2022-09-23 07:38
If you look in the wiki you will find the info, for 2.34 for instance the magic link is http://trac.webkit.org/wiki/WebKitGTK/2.34.x

**Comment by austinchenji** [comment] 2022-09-23 08:44
Great, it is based on [281844](https://trac.webkit.org/changeset/281844/webkit).
Thanks, @philn.
I thought I can get that kind of information in wpe release tar ball.

**Comment by philn** [comment] 2022-09-23 13:55
> I thought I can get that kind of information in wpe release tar ball.

Hum yes, it might be a good idea indeed. CCing our release manager @aperezdc 

I'll close this then. If you have more questions don't hesitate to create a new "discussion" instead of an issue!

**Closed by philn** 2022-09-23 13:55 UTC
Labels: question
